213038/Clinicapp/Controllers/Api/PatientsController.cs
using AutoMapper;
using ClinicManagement.Core;
using ClinicManagement.Core.Dto;
using ClinicManagement.Core.Models;
using System.Linq;
using System.Web.Http;

namespace ClinicManagement.Controllers.Api
{
    public class PatientsController : ApiController
    {
        private readonly IUnitOfWork _unitOfWork;
        public PatientsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;

        }

        public IHttpActionResult GetPatients()
        {
            var patientsQuery = _unitOfWork.Patients.GetPatients();


            var patientDto = patientsQuery.ToList()
                                          .Select(Mapper.Map<Patient, PatientDto>);

            return Ok(patientDto);

        }


        [HttpDelete]
        public IHttpActionResult Delete(int id)
        {
            var patient = _unitOfWork.Patients.GetPatient(id);
            _unitOfWork.Patients.Remove(patient);
            _unitOfWork.Complete();
            return Ok();
        }

    }
}

213038/Clinicapp/Controllers/AttendancesController.cs
using System;
using System.Web.Mvc;
using ClinicManagement.Core;
using ClinicManagement.Core.Models;
using ClinicManagement.Core.ViewModel;

namespace ClinicManagement.Controllers
{
    [Authorize]
    public class AttendancesController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public AttendancesController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public ActionResult Details(int id)
        {
            var attendance = _unitOfWork.Attandences.GetAttendance(id);
            return View("_attendancePartial", attendance);
        }

        public ActionResult Create(int id)
        {
            var viewModel = new AttendanceFormViewModel
            {
                Patient = id,
                Heading = "Add Attendance"
            };
            return View("AttendanceForm", viewModel);
        }

        [HttpPost]
        public ActionResult Create(AttendanceFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
                return View("AttendanceForm", viewModel);

            var attendance = new Attendance
            {
                Id = viewModel.Id,
                ClinicRemarks = viewModel.ClinicRemarks,
                Diagnosis = viewModel.Diagnosis,
                SecondDiagnosis = viewModel.SecondDiagnosis,
                ThirdDiagnosis = viewModel.ThirdDiagnosis,
                Therapy = viewModel.Therapy,
                Date = DateTime.Now,
                Patient = _unitOfWork.Patients.GetPatient(viewModel.Patient)
            };
            _unitOfWork.Attandences.Add(attendance);
            _unitOfWork.Complete();
            //ViewBag.Confirm = "Successfully Saved";
            //return PartialView("_Confirmation");
            return RedirectToAction("Details", "Patients", new { id = viewModel.Patient });
        }



    }
}

213038/Clinicapp/Controllers/PatientsController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using ClinicManagement.Core;
using ClinicManagement.Core.Models;
using ClinicManagement.Core.ViewModel;

namespace ClinicManagement.Controllers
{
    [Authorize(Roles = RoleName.DoctorRoleName + "," + RoleName.AdministratorRoleName)]
    public class PatientsController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public PatientsController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Details(int id)
        {
            var viewModel = new PatientDetailViewModel()
            {
                Patient = _unitOfWork.Patients.GetPatient(id),
                Appointments = _unitOfWork.Appointments.GetAppointmentWithPatient(id),
                Attendances = _unitOfWork.Attandences.GetAttendance(id),
                CountAppointments = _unitOfWork.Appointments.CountAppointments(id),
                CountAttendance = _unitOfWork.Attandences.CountAttendances(id)
            };
            return View("Details", viewModel);
        }




        [Authorize]
        public ActionResult Create()
        {
            var viewModel = new PatientFormViewModel
            {
                Cities = _unitOfWork.Cities.GetCities(),
                Heading = "New Patient"
            };
            return View("PatientForm", viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PatientFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Cities = _unitOfWork.Cities.GetCities();
                return View("PatientForm", viewModel);

            }

            var patient = new Patient
            {
                Name = viewModel.Name,
                Phone = viewModel.Phone,
                Address = viewModel.Address,
                DateTime = DateTime.Now,
                BirthDate = viewModel.GetBirthDate(),
                Height = viewModel.Height,
                Weight = viewModel.Weight,
                CityId = viewModel.City,
                Sex = viewModel.Sex,
                Token = (2018 + _unitOfWork.Patients.GetPatients().Count()).ToString().PadLeft(7, '0')
            };

            _unitOfWork.Patients.Add(patient);
            _unitOfWork.Complete();
            return RedirectToAction("Index", "Patients");

            // TODO: BUG redirect to detail 
            //return RedirectToAction("Details", new { id = viewModel.Id });
        }


        public ActionResult Edit(int id)
        {
            var patient = _unitOfWork.Patients.GetPatient(id);

            var viewModel = new PatientFormViewModel
            {
                Heading = "Edit Patient",
                Id = patient.Id,
                Name = patient.Name,
                Phone = patient.Phone,
                Date = patient.DateTime,
                //Date = patient.DateTime.ToString("d MMM yyyy"),
                BirthDate = patient.BirthDate.ToString("dd/MM/yyyy"),
                Address = patient.Address,
                Height = patient.Height,
                Weight = patient.Weight,
                Sex = patient.Sex,
                City = patient.CityId,
                Cities = _unitOfWork.Cities.GetCities()
            };
            return View("PatientForm", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(PatientFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                viewModel.Cities = _unitOfWork.Cities.GetCities();
                return View("PatientForm", viewModel);
            }


            var patientInDb = _unitOfWork.Patients.GetPatient(viewModel.Id);
            patientInDb.Id = viewModel.Id;
            patientInDb.Name = viewModel.Name;
            patientInDb.Phone = viewModel.Phone;
            patientInDb.BirthDate = viewModel.GetBirthDate();
            patientInDb.Address = viewModel.Address;
            patientInDb.Height = viewModel.Height;
            patientInDb.Weight = viewModel.Weight;
            patientInDb.Sex = viewModel.Sex;
            patientInDb.CityId = viewModel.City;

            _unitOfWork.Complete();
            return RedirectToAction("Index", "Patients")
;
        }



    }
}

213038/Clinicapp/Views/Patients/Details.cshtml
@using ClinicManagement.Core.Models
@model ClinicManagement.Core.ViewModel.PatientDetailViewModel
@{
    ViewBag.Title = "Details";
}
<!-- load partial here-->
<div id="MyModal" class="modal fade in">
        <div class="modal-dialog "style="width: 900px;">
            <div class="modal-content">
                <div id="MyModalContent"></div>
            </div>
        </div>
    </div>


<div class="page-title">
    <div class="title_left">
        <h3>Details</h3>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            @*<div class="x_title">
                <h2>Patient Details </h2>
                <ul class="nav navbar-right panel_toolbox">
                    <li> <a href="@Url.Action("Edit", "Patients", new { id= Model.Patient.Id})" class="btn-link"><i class="fa fa-edit m-right-xs"></i>Edit</a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>*@

            <div class="x_content">
                <div class="col-md-3 col-sm-3 col-xs-12 profile_left ">
                    <div class="profile_img">
                        <div id="crop-avatar">
                            <!-- Current avatar -->
                            <img class="img-responsive avatar-view" src="~/Content/images/user.png">
                        </div>
                    </div>
                    <h3>@Model.Patient.Name</h3>
                    <ul class="list-unstyled user_data">
                        <li> <i class="fa fa-user"><strong>Token:</strong> @Model.Patient.Token</i></li>
                        <li> <i class="fa fa-user"><strong>Sex:</strong> @Model.Patient.Sex</i></li>
                        <li> <i class="fa fa-user"><strong>Age:</strong> @Model.Patient.Age</i></li>
                        <li> <i class="fa fa-user"><strong>Height:</strong> @Model.Patient.Height</i></li>
                        <li> <i class="fa fa-user"><strong>Weight:</strong> @Model.Patient.Weight</i></li>
                        <li>
                            <i class="fa fa-map-marker user-profile-icon"></i><strong>Address:</strong> @Model.Patient.Address, @Model.Patient.Cities.Name
                        </li>

                        <li>
                            <i class="fa fa-phone"></i><strong>Phone:</strong> @Model.Patient.Phone
                        </li>
                        <li class="m-top-xs">
                            <i class="fa fa-clock-o"></i><strong>Date :</strong> @Model.Patient.DateTime.ToString("MMM"), @Model.Patient.DateTime.ToString("d ")- @Model.Patient.DateTime.ToString("yyyy")-@Model.Patient.DateTime.ToString("HH:mm")

                        </li>
                    </ul>
                    <a href="@Url.Action("Edit", "Patients", new { id= Model.Patient.Id})" class="btn btn-success"><i class="fa fa-edit m-right-xs"></i>Edit</a>

                    <br/>
                </div>
                <div class="col-md-9 col-sm-9 col-xs-12">
                    <div class="col-md-6 col-sm-6 col-xs-12">
                       <span class="section"> Appointment</span>
                      <a id="patientID" data-appointment-id="@Model.Patient.Id" href="#"> Patient Appointment</a>  <span class="badge badge-error">@Model.CountAppointments</span> @if (User.IsInRole(RoleName.AdministratorRoleName))
                                                                                                                                                                                   {
                                                                                                                                                                                       <a href="@Url.Action("Create", "Appointments", new {id = Model.Patient.Id})"><i class="fa fa-plus"></i></a>
                                                                                                                                                                                   }
                    </div>          
                    <div class="col-md-6 col-sm-6 col-xs-12">
                       <span class="section">Attendance </span>
                        <a id="attendanceID" data-attendance-id="@Model.Patient.Id" href="#"> Lab Attendance </a> <span class="badge badge-error">@Model.CountAttendance</span> <a href="@Url.Action("Create", "Attendances", new { id=Model.Patient.Id})"> <i class="fa fa-plus"></i></a>
                    </div>
                    @*<div class="" role="tabpanel" data-example-id="togglable-tabs">
                        <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                            <li role="presentation" class="active">
                                <a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true">Appointment history</a>

                            </li>
                            <li role="presentation" class="">
                                <a href="#tab_content2" role="tab" id="profile-tab" data-toggle="tab" aria-expanded="false">Attendance history</a>                            
                                </li>
                        </ul>
                        <div id="myTabContent" class="tab-content">
                            <div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
                                <!-- start appointment history -->
                                <table class="data table table-striped no-margin dataTables">
                                    <thead>
                                        <tr>
                                            <th>Doctor</th>
                                            <th>Date</th>
                                            <th>Time</th>
                                            <th>Details</th>
                                            <th>Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var item in Model.Appointments)
                                        {
                                            <tr>
                                                <td>@item.Doctor.Name</td>
                                                <td>@item.StartDateTime.ToString("MMM"),@item.StartDateTime.ToString("d ")-@item.StartDateTime.ToString("yyyy")</td>
                                                <td>@item.StartDateTime.ToString("HH:mm")</td>
                                                <td>@item.Detail</td>
                                                <td>
                                                    @{
                                                        if (item.Status == true)
                                                        {
                                                            <a href="#" style="padding: 3px 10px 3px 10px; background-color:green " class="badge" readonly>Approved</a>
                                                        }
                                                        else
                                                        {
                                                            <a href="#" style="padding: 3px 10px 3px 10px; background-color:greenyellow " class="badge" readonly>Pending</a>
                                                        }
                                                    }
                                                </td>

                                            </tr>

                                                        }
                                    </tbody>
                                </table>
                                <!-- end appointment history -->
                            </div>
                            <div role="tabpanel" class="tab-pane fade" id="tab_content2" aria-labelledby="profile-tab">
                                <table class="data table table-striped no-margin dataTables">
                                    <thead>
                                    <tr>
                                        <th>Clinic Remarks</th>
                                        <th>Diagnosis</th>
                                        <th>Second Diagnosis</th>
                                        <th>Third Diagnosis</th>
                                        <th>Therapy</th>
                                        <th>Date</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach (var item in Model.Attendances)
                                    {
                                        <tr>
                                            <td>@item.ClinicRemarks</td>
                                            <td>@item.Diagnosis</td>
                                            <td>@item.SecondDiagnosis</td>
                                            <td>@item.ThirdDiagnosis</td>
                                            <td>@item.Therapy</td>
                                            <td>@item.Date.ToString("MMM"), @item.Date.ToString("d ")-@item.Date.ToString("yyyy")</td>
                                        </tr>

                                    }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>*@
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(document).ready(function(){
            $("#patientID").on("click", function () {
                var link = $(this);
                $.ajaxSetup({ cache: false });
                var detailUrl = "/Appointments/Details/" + link.attr("data-appointment-id");
                $("#MyModalContent").load(detailUrl, function () {
                    $("#MyModal").modal({
                        keyboard: false
                    }, 'show');

                });
                return false;
            });
            $("#attendanceID").on("click", function () {
                var link = $(this);
                $.ajaxSetup({ cache: false });
                var detailUrl = "/Attendances/Details/" + link.attr("data-attendance-id");
                $("#MyModalContent").load(detailUrl, function () {
                    $("#MyModal").modal({
                        keyboard: false
                    }, 'show');

                });
                return false;
            });


        });

        $('.dataTables').DataTable({
            "scrollY": "300px",
            "scrollCollapse": true,
            "paging": false,
            "filter": false,
            "info": false
        });
    </script>
 
}

213038/Clinicapp/Views/Patients/Index.cshtml
@model IEnumerable<ClinicManagement.Core.Models.Patient>
    @{
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

<div class="page-title">
    <div class="title_left">
        <h3>Patients</h3>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">

                <table id="patients" class="data table table-striped no-margin">
                    <thead>
                        <tr>
                            <th>Token</th>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Address</th>
                            <th>City</th>
                            <th><a href="@Url.Action("Create","Patients")" class="btn btn-primary btn-xs"><i class="fa fa-edit"></i>Add</a></th>

                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@section scripts
{

    <script>
        var popup;

        $(document).ready(function () {
            var table = $("#patients").DataTable({
                ajax: {
                    url: "/api/patients",
                    dataSrc: ""
                },
                columns: [
                    {
                        data: "token"
                        
                    },
                    {
                        data: "name"
                    },
                    {
                        data: "phone",
                        render: function (data) {
                            return data.toString().replace(
                              /(\d\d\d)(\d\d\d)(\d\d\d\d)/g, '$1-$2-$3');
                        }
                    },
                    {
                        data: "address"
                    },
                    {
                        data: "cities.name"
                    },
                    {
                        data: "id",
                        render: function (data, type, patient) {
                            return "<a href='/patients/details/ " + patient.id + "' class='btn btn-default btn-xs'>" + "<i class='fa fa-folder'></i>View</a>" +
                                //"<button class= 'btn-link js-detail' data-detail-id=" + data + "><i class='fa fa-pencil-square'></i></button>" +
                                "<button class= 'btn btn-danger btn-xs js-delete' data-patient-id=" + data + "><i class='fa fa-trash-o'></i>Delete</button>";
                        }
                    }

                ]
            });


          


            $("#patients").on("click", ".js-delete", function () {
                var button = $(this);

                bootbox.confirm("Are you sure to delete this patient?", function (result) {
                    if (result) {
                        $.ajax({
                            url: "/api/patients/" + button.attr("data-patient-id"),
                            method: "DELETE",
                            success: function () {
                                table.row(button.parents("tr")).remove().draw();
                            }
                        });
                    }
                });
            });




        });

    </script>
}

213038/Clinicapp/Views/Patients/PatientForm.cshtml
@model ClinicManagement.Core.ViewModel.PatientFormViewModel
@{
    ViewBag.Title = Model.Heading;
}
<div class="row ">
    <div class="col-md-12 col-sm-12 col-xs-12">

        <div class="x_panel">
            <div class="x_content">
                @using (Html.BeginForm(Model.Action, "Patients", FormMethod.Post, new { @class = "form-horizontal form-label-left", autocomplete = "off" }))
                {


                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(m => m.Id)

                    <span class="section">Add Patient</span>
                    <div class="form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12">Name <span class="required">*</span></label>
                        <div class="col-md-6 col-sm-6 col-xs-12"> 
                            @Html.TextBoxFor(m => m.Name, new { @class = "form-control col-md-7 col-xs-12", autofocus="true" })
                            @Html.ValidationMessageFor(m => m.Name)
                        </div>
                    </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Gender <span class="required">*</span></label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.DropDownListFor(m => m.Sex, Model.GendersList, new { @class = "form-control col-md-7 col-xs-12" })
                                @Html.ValidationMessageFor(m => m.Sex)
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">BirthDate <span class="required">*</span></label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(m => m.BirthDate, new { @class = "form-control col-md-7 col-xs-12 datepicker " })
                                @Html.ValidationMessageFor(m => m.BirthDate)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Height</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(m => m.Height, new { @class = "form-control col-md-7 col-xs-12" })
                                @Html.ValidationMessageFor(m => m.Height)
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Weight</label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(m => m.Weight, new { @class = "form-control col-md-7 col-xs-12" })
                                @Html.ValidationMessageFor(m => m.Weight)
                            </div>
                        </div>

                        <div class=" form-group">
                            <label class="control-label col-sm-3 col-xs-12">Phone <span class="required">*</span></label>
                            <div class="col-md-6 col-sm-6 col-xs-12">

                                @Html.TextBoxFor(m => m.Phone, new { @class = "form-control col-md-7 col-xs-12" })
                                @Html.ValidationMessageFor(m => m.Phone)
                            </div>
                        </div>


                        <div class="form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">Address <span class="required">*</span></label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.TextBoxFor(m => m.Address, new { @class = "form-control col-md-7 col-xs-12" })
                                @Html.ValidationMessageFor(m => m.Address)
                            </div>
                        </div>

                        <div class=" form-group">
                            <label class="control-label col-md-3 col-sm-3 col-xs-12">City <span class="required">*</span></label>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                @Html.DropDownListFor(m => m.City, new SelectList(Model.Cities, "Id", "Name"), "Select", new { @class = "form-control col-md-7 col-xs-12" })
                                @Html.ValidationMessageFor(m => m.City)
                            </div>
                        </div>
                            <div class="ln_solid"></div>
                            <div class="form-group">
                                <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-4">
                                    <button type="submit" class="btn btn-success">Save</button>
                                </div>
                            </div>

                }


            </div>
        </div>
    </div>

</div>
@section scripts{
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {

            $('.datepicker').datepicker({
                format: 'dd/mm/yyyy',
                //clearBtn: true,
                todayHighlight: true,
                //todayBtn: true,
                //todayBtn: 'linked',
                orientation: "top left",
                autoclose: true
            });

        });
    </script>

}